spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./.database/bankdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
#    database-platform: org.hibernate.dialect.H2Dialect
